### ISSUE TITLE
clean up ot:curatorName values with "(None)"

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/phylesystem-1#9]
These were created as a result of https://github.com/OpenTreeOfLife/opentree/issues/982. Ideally, we'd capture any proper names since assigned to a GitHub profile, but we should at least trim these to the bare GitHub userid.

**Comment by jimallman** [comment]
You can see the target studies using the study-list filter, like so:

https://tree.opentreeoflife.org/curator/?match=(None)

**Comment by jar398** [comment]
I believe this is fixed by ccba06cac03dbe082deccf617c486b0be7abbcf8 .
